version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "stox"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge